# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('about', models.TextField(default=models.CharField(max_length=100), max_length=400)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('dettagli', models.TextField(max_length=255)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('immagine', models.FileField(upload_to=b'')),
                ('dimensione', models.CharField(choices=[('P', 'Piccolo'), ('M', 'Medio'), ('G', 'Grande')], max_length=1)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Casa')),
            ],
        ),
    ]
