# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20170326_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='data_rilascio',
            field=models.DateField(default=datetime.datetime(2017, 3, 26, 13, 33, 16, 618494, tzinfo=utc)),
        ),
    ]
